/**
 * @Variables below will used when we will
 * make a transition from monolit to microservices

 * KAFKA_PORT: 'KAFKA_PORT',
 * KAFKA_HOST: 'KAFKA_HOST',
 * SERVICE_NAME: 'SERVICE_NAME',
 * KAFKA_BROKERS: 'KAFKA_BROKERS',
 * KAFKA_GROUP_ID: 'KAFKA_GROUP_ID',
 */

export const ENV_VARIABLES = {
  JWT_SECRET: 'JWT_SECRET',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  MONGO_HOST: 'MONGO_HOST',
  MONGO_PORT: 'MONGO_PORT',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  MONGO_DB_NAME: 'MONGO_DB_NAME',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  POSTGRES_USERNAME: 'POSTGRES_USERNAME',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  POSTGRES_USER_DB_NAME: 'POSTGRES_USER_DB_NAME',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
};
