# ================= NETWORK =================
bind 0.0.0.0
protected-mode no
port 6379

# ================= SECURITY =================
# requirepass strongpassword
# (лучше брать из env, но redis.conf env не читает напрямую)

# ================= PERSISTENCE =================
dir /data

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

# ================= MEMORY =================
maxmemory 512mb
maxmemory-policy allkeys-lru

# ================= GENERAL =================
databases 16
timeout 0
tcp-keepalive 300

# ================= REDIS PASSWORD =================
requirepass myStrongPassword

notify-keyspace-events Ex